-- PROCEDURE: public.create_plots()

-- DROP PROCEDURE IF EXISTS public.create_plots();

CREATE OR REPLACE PROCEDURE public.create_plots(
	)
LANGUAGE 'sql'
AS $BODY$
CREATE TABLE IF NOT EXISTS public.plots
(
    plot_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    div character varying COLLATE pg_catalog."default",
    script character varying COLLATE pg_catalog."default",
    experiment_id integer NOT NULL,
    group_id integer NOT NULL,
    observation_id integer NOT NULL,
    variable_id integer NOT NULL,
    CONSTRAINT plots_pkey PRIMARY KEY (plot_id),
    CONSTRAINT plots_experiment_id_group_id_o_78d8b74e_uniq UNIQUE (experiment_id, group_id, observation_id, variable_id),
    CONSTRAINT plots_experiment_id_79cb5574_fk_experiments_experiment_id FOREIGN KEY (experiment_id)
        REFERENCES public.experiments (experiment_id) 
        ON DELETE CASCADE,
    CONSTRAINT plots_group_id_85eaf2d2_fk_groups_group_id FOREIGN KEY (group_id)
        REFERENCES public.groups (group_id) 
        ON DELETE CASCADE,
    CONSTRAINT plots_observation_id_26813e98_fk_observations_observation_id FOREIGN KEY (observation_id)
        REFERENCES public.observations (observation_id) 
        ON DELETE CASCADE,
    CONSTRAINT plots_variable_id_394e0899_fk_variables_variable_id FOREIGN KEY (variable_id)
        REFERENCES public.variables (variable_id) 
        ON DELETE CASCADE
)



-- CREATE TABLE IF NOT EXISTS plots (
-- 	plot_id serial PRIMARY KEY,
-- 	div VARCHAR,
-- 	script VARCHAR,
-- 	experiment_id INTEGER NOT NULL,
-- 	group_id INTEGER NOT NULL,
-- 	observation_id INTEGER NOT NULL,
-- 	variable_id INTEGER NOT NULL,
-- 	CONSTRAINT fk_experiment
-- 		FOREIGN KEY (experiment_id)
-- 			REFERENCES experiments(experiment_id)
-- 			ON DELETE CASCADE,
-- 	CONSTRAINT fk_group
-- 		FOREIGN KEY (group_id)
-- 			REFERENCES groups(group_id)
-- 			ON DELETE CASCADE,
-- 	CONSTRAINT fk_observation
-- 		FOREIGN KEY (observation_id)
-- 			REFERENCES observation_variable(observation_id)
-- 			ON DELETE CASCADE,
-- 	CONSTRAINT fk_variable
-- 		FOREIGN KEY (variable_id)
-- 			REFERENCES variables(variable_id)
-- 			ON DELETE CASCADE,
-- 	UNIQUE(experiment_id, group_id, observation_id, variable_id)

$BODY$;
ALTER PROCEDURE public.create_plots()
    OWNER TO postgres;
