# Generated by Django 4.2.10 on 2024-07-25 15:29

from django.db import migrations

READERS = [
    'IodaObsSpace',
    'SocaRestart',
    'JediLog'
]

ALIASES = {
    'IodaObsSpace': [
        ('Observation', 'Observation'),
        ('Group', 'Plots'),
        ('Variable', 'Variable'),
    ],
    'SocaRestart': [
        ('Observation', 'SOCA'),
        ('Group', 'SocaVars'),
        ('Variable', 'Variable'),
    ],
    'JediLog': [
        ('Observation', 'JediLog'),
        ('Group', 'Log Options'),
        ('Variable', 'Variable'),
    ],
}

def populate_readers_and_aliases(apps, schema_editor):
    Reader = apps.get_model('api', 'Readers')
    Alias = apps.get_model('api', 'Aliases')

    for reader_name in READERS:
        reader, created = Reader.objects.get_or_create(reader_name=reader_name)
        for alias_name, alias_value in ALIASES[reader_name]:
            Alias.objects.get_or_create(alias_name=alias_name, alias_value=alias_value, reader=reader)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_readers_and_aliases),
    ]
